width: 25
height: 25
depot: [2, 2]
hospitals:
  - [20, 3]
  - [5, 20]
  - [22, 22]
buildings:
  - [8, 8]
  - [9, 8]
  - [10, 8]
  - [8, 9]
  - [8, 10]
  - [15, 15]
  - [16, 15]
  - [15, 16]
  - [16, 16]
initial_fires:
  - [12, 5]
  - [6, 12]
  - [18, 18]
  - [10, 20]
rubble:
  - [11, 11]
  - [12, 11]
  - [11, 12]
  - [12, 12]
  - [7, 7]
  - [14, 14]
survivors: 20