width: 20
height: 20
depot: [1, 1]
hospitals:
  - [17, 2]
  - [15, 15]
buildings:
  - [5,5]
  - [5,6]
  - [6,5]
  - [10,10]
  - [11,10]
  - [12,10]
initial_fires:
  - [8, 3]
  - [12, 12]
rubble:
  - [7, 7]
  - [7, 8]
  - [8, 7]
survivors: 15
